name: .NET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: 
      name: test
      url: https://github.com/mattiasvikstrom/SalarySystemDevelopment/tree/dev
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
  test:
    runs-on: ubuntu-latest
    name: Unit tests
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      working-directory: ./SalarySystemTests
      run: dotnet test --verbosity normal
      
  integrationtest:
    runs-on: ubuntu-latest
    name: Integration tests
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Test integration
        working-directory: ./SalarySystemTestsIntegration
        run: dotnet test --verbosity normal
        
  deploy:
    needs: [test, integrationtest]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploying"
